# Generated by Django 3.0.12 on 2021-08-08 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210808_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='images/aniverse.png', upload_to=''),
        ),
    ]
