# Generated by Django 3.0.12 on 2021-08-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210808_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='aniverse.png', upload_to=''),
        ),
    ]
