# Generated by Django 3.0.12 on 2021-08-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210808_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='C:/Users/Lenovo/desktop/Django/aniverse/static/aniverse.png', upload_to=''),
        ),
    ]
