# Generated by Django 3.0.12 on 2021-08-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210808_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('year_published', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=100)),
                ('image', models.ImageField(default='aniverse.png', upload_to='')),
            ],
        ),
    ]
