# Generated by Django 3.0.12 on 2021-08-09 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_articleitems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articleitems',
            old_name='year_published',
            new_name='created',
        ),
    ]
