# Generated by Django 3.0.12 on 2021-08-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210809_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleitems',
            name='url',
            field=models.SlugField(),
        ),
    ]
