# Generated by Django 3.0.12 on 2021-08-09 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210809_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articleitems',
            old_name='url',
            new_name='slug',
        ),
    ]
