# Generated by Django 3.0.12 on 2021-08-11 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210811_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleitems',
            name='created',
        ),
    ]
