# Generated by Django 3.0.12 on 2021-08-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_articleitems_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleitems',
            name='name',
            field=models.CharField(default='Example Title Name', max_length=40),
        ),
    ]
