# Generated by Django 3.0.12 on 2021-08-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20210811_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleitems',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
