# Generated by Django 3.0.12 on 2021-08-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20210811_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('image', models.ImageField(default='aniverse.png', upload_to='')),
            ],
            options={
                'verbose_name_plural': 'UserAccounts',
            },
        ),
    ]
