# Generated by Django 3.0.12 on 2021-08-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_useraccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='slug',
            field=models.SlugField(default='example'),
            preserve_default=False,
        ),
    ]
