# Generated by Django 3.0.12 on 2021-08-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_useraccount_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='country',
            field=models.CharField(default='Country', max_length=100),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='last_name',
            field=models.CharField(default='Last Name', max_length=100),
        ),
    ]
